AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AI Quiz Generator App (dil-ai-build-day-2026)

Globals:
  Function:
    Timeout: 30
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  DynamoDbStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: stacks/dynamodb/template.yaml

  BedrockStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: stacks/bedrock/template.yaml

  UploadsStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: stacks/uploads/template.yaml

  ApiStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: stacks/api/template.yaml
      Parameters:
        BedrockInvokePolicyArn: !GetAtt BedrockStack.Outputs.BedrockInvokePolicyArn
        QuizTableArn: !GetAtt DynamoDbStack.Outputs.QuizTableArn
        QuizTableName: !GetAtt DynamoDbStack.Outputs.QuizTableName
        UploadsBucketName: !GetAtt UploadsStack.Outputs.UploadsBucketName
        UploadsBucketArn: !GetAtt UploadsStack.Outputs.UploadsBucketArn

  FrontendStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: stacks/frontend/template.yaml

Outputs:
  FrontendBucketName:
    Value: !GetAtt FrontendStack.Outputs.FrontendBucketName
  FrontendWebsiteUrl:
    Value: !GetAtt FrontendStack.Outputs.FrontendWebsiteUrl
  ApiGatewayUrl:
    Value: !GetAtt ApiStack.Outputs.ApiBaseUrl
