AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Gateway + Lambda

Parameters:
  BedrockInvokePolicyArn:
    Type: String
  QuizTableArn:
    Type: String
  QuizTableName:
    Type: String

Globals:
  Function:
    Timeout: 30
    Tracing: Active
    Environment:
      Variables:
        TABLE_NAME: !Ref QuizTableName

  Api:
    TracingEnabled: true
    Cors:
      AllowOrigin: "'*'"
      AllowMethods: "'GET,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"

Resources:
  QuizAppApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../api
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures: [x86_64]
      Policies:
        - !Ref BedrockInvokePolicyArn
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:UpdateItem
                - dynamodb:Query
              Resource: !Ref QuizTableArn
      Events:
        CreateQuiz:
          Type: Api
          Properties:
            Path: /create
            Method: get
        SubmitAnswers:
          Type: Api
          Properties:
            Path: /submit
            Method: get
        EvaluateAnswers:
          Type: Api
          Properties:
            Path: /evaluate
            Method: get
        HealthCheck:
          Type: Api
          Properties:
            Path: /healthz
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints: [app.ts]

Outputs:
  ApiBaseUrl:
    Description: API base URL (Prod stage)
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod'
  FunctionArn:
    Value: !GetAtt QuizAppApiFunction.Arn
  FunctionRoleArn:
    Value: !GetAtt QuizAppApiFunctionRole.Arn
